name: Build & Deploy
on:
  workflow_dispatch:
jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          JAVA_HOME: /usr/lib/jvm/java-11-amazon-corretto
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:openjdk-r/ppa
          sudo apt-get install -y java-common
          wget -nv https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.deb
          sudo dpkg --install amazon-corretto-11-x64-linux-jdk.deb
          rm amazon-corretto-11-x64-linux-jdk.deb
          cd signaling
          ./gradlew bootJar

#      - uses: hashicorp/packer-github-actions@master
#        with:
#          command: build
#          arguments: "-color=false -on-error=abort"
#          target: signaling.pkr.hcl
#        env:
#          PACKER_LOG: 1
