name: Build & Deploy
on:
  push:
jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./signaling/gradlew -v

#      - uses: hashicorp/packer-github-actions@master
#        with:
#          command: build
#          arguments: "-color=false -on-error=abort"
#          target: signaling.pkr.hcl
#        env:
#          PACKER_LOG: 1