name: Build & Deploy
on:
  push:
jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:openjdk-r/ppa
          sudo apt-get install -y java-common
          wget https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.deb
          sudo dpkg --install amazon-corretto-11-x64-linux-jdk.deb
          rm amazon-corretto-11-aarch64-linux-jdk.deb
          ./signaling/gradlew -v

#      - uses: hashicorp/packer-github-actions@master
#        with:
#          command: build
#          arguments: "-color=false -on-error=abort"
#          target: signaling.pkr.hcl
#        env:
#          PACKER_LOG: 1
